### ISSUE TITLE
Solidity send() and transfer() functions doesn't work as expected

### ISSUE THREAD

**Issue by jessielesbian** [mintme-com/webchaind#10]
I am trying to deploy a dividends-paying token on the MintME blockchain. When I tried to withdraw dividends, it reverted. Subsequent testing showed that MintME's VM failed to properly implement the solidity send() and transfer() functions.

*Additional information from the token owner*
It failed on this line, since MintME doesn't have transfer()
![unknown](https://user-images.githubusercontent.com/52745229/119323509-72596480-bc87-11eb-962f-d2d8c63a228d.png)

This is where the blockchain IPO code failed.
And since MintME mis-implemented send()/transfer(), it failed.
![unknown1](https://user-images.githubusercontent.com/52745229/119323638-99179b00-bc87-11eb-8fa2-0a2c2805ca20.png)

**Comment by tendo-abc** [comment]
Pls provide source code, deployed contract address, and the way you compiled and deployed it

**Comment by jessielesbian** [comment]
Its Solidity 0.4.24 compiled using Remix. The're a sufficient balance guarantee and the address involved does not belong to a smart contract.

**Comment by tendo-abc** [comment]
webchaind is obsolete now
